<?php

namespace AppBundle\Repository;

/**
 * IsLikedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsLikedRepository extends \Doctrine\ORM\EntityRepository
{
    public function isLike($roadtrip, $userId){
        $query = $this->createQueryBuilder('i')
            ->join('i.roadtripId', 'r')
            ->join('i.userId', 'u')
            ->where('r.id = :roadtrip')
            ->setParameter('roadtrip', $roadtrip)
            ->andWhere('u.id = :user')
            ->setParameter('user', $userId)
            ->getQuery();

        return $query->getResult();
    }

    public function showFavoriteLimited($userId, $limit, $offset){
        $query = $this->createQueryBuilder('i')
            ->join('i.userId', 'u')
            ->where('u.id = :user')
            ->setParameter('user', $userId)
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->orderBy('i.id', 'desc')
            ->getQuery();

        return $query->getResult();
    }
}
